"""Generates a children's story using the local LLM, page by page."""

import json
from typing import TypedDict

import ollama


class StoryPage(TypedDict):
    page_num: int
    page_type: str  # "cover", "dedication", "opening", "rising_action", "climax", "resolution", "final"
    title: str
    text: str
    illustration_prompt: str


class StoryRequest(TypedDict):
    story_topic: str
    child_age: int
    child_name: str | None
    main_character: str | None
    story_theme: str
    moral_lesson: str | None
    dedicated_to: str | None


def _get_age_tier(age: int) -> tuple[str, int, int, int]:
    """Map age to tier and constraints."""
    if age <= 4:
        return "Tier 1: Early Listeners", 6, 8, 3
    elif age <= 7:
        return "Tier 2: Early Readers", 10, 12, 5
    else:
        return "Tier 3: Independent Readers", 12, 16, 8


def generate_story(req: StoryRequest) -> list[StoryPage]:
    """Generate a complete story as a list of pages, using Ollama."""

    tier_name, min_pages, max_pages, max_sentences_per_page = _get_age_tier(req["child_age"])

    # Build the prompt
    prompt = f"""You are a professional children's story writer. Your task is to write a complete children's story in exactly the following format: a JSON array of pages.

CRITICAL CONSTRAINTS:
1. The story MUST be exactly {min_pages}-{max_pages} pages (excluding cover and dedication).
2. Each page MUST contain exactly one of these page types in order: cover, [dedication], opening, rising_action, climax, resolution, final.
3. Each body page has at most {max_sentences_per_page} sentences.
4. The story is for a {req['child_age']}-year-old ({tier_name}).
5. Use simple, age-appropriate vocabulary and sentence structure.
6. The character name is: {req['child_name'] or req['main_character'] or 'a character'}
7. Theme/mood: {req['story_theme']}
8. Moral lesson: {req['moral_lesson'] or 'infer the most natural moral from the topic'}
9. NO violence, death, scary content, sexual content, or mockery.
10. Every sentence must be grammatically perfect.
11. The story must read as if written by a thoughtful human, not generated by AI.

STORY IDEA: {req['story_topic']}

OUTPUT RULES:
- Return ONLY a valid JSON array of page objects.
- Each page object has keys: "page_num", "page_type", "title", "text", "illustration_prompt"
- page_num: 1-indexed integer
- page_type: one of: cover, dedication, opening, rising_action, climax, resolution, final
- title: the title of the story (same for all pages)
- text: the page content (empty string for cover page)
- illustration_prompt: a detailed visual prompt for the illustration on this page (e.g., "A brown rabbit sitting under a tree, looking sad but hopeful, soft watercolor style")

Example structure (do not copy content, only format):
[
  {{"page_num": 1, "page_type": "cover", "title": "The Happy Day", "text": "", "illustration_prompt": "..."}},
  {{"page_num": 2, "page_type": "opening", "title": "The Happy Day", "text": "Once upon a time...", "illustration_prompt": "..."}},
  ...
]

NOW WRITE THE COMPLETE STORY:
"""

    response = ollama.generate(
        model="gemma3:12b",
        prompt=prompt,
        stream=False,
    )

    # Parse the JSON response
    response_text = response["response"].strip()

    # Try to find and extract JSON from the response
    try:
        # Find the JSON array in the response
        start_idx = response_text.find("[")
        end_idx = response_text.rfind("]") + 1
        if start_idx == -1 or end_idx == 0:
            raise ValueError("No JSON array found in response")

        json_str = response_text[start_idx:end_idx]
        pages: list[StoryPage] = json.loads(json_str)

        return pages
    except (json.JSONDecodeError, ValueError) as e:
        raise ValueError(f"Failed to parse story JSON from LLM response: {e}\n\nResponse:\n{response_text}")
